### ISSUE TITLE
getQueryParam includes #

### ISSUE THREAD

**Issue by zimt28** [kadirahq/flow-router#225] opened 2015-07-27 09:16 UTC
Let's assume I have a url like `localhost:3000/shippings?filter=incoming`. When I call `getQueryParam('filter')`, I get `incoming`, just as expected.

However, if my url contains a hash from some *div* buttons with `href="#"` like `localhost:3000/shippings?filter=incoming#`, `getQueryParam('filter')` will return that hash as well: `incoming#`.

I'm not sure here if people use hashes in their query params, but at least hashes at the end should be filtered.

**Comment by arunoda** [comment] 2015-07-28 00:42
I think no one will use hash in queryParams. I think we don't allow them to do it. I think we can fix this.
@delgermurun can you look at this.

**Comment by arunoda** [comment] 2015-07-28 00:42
I think we can ignore the content after `#` in the querystring.

**Comment by arunoda** [comment] 2015-07-28 00:43
May be this could be the last bug fix before 2.0

**Comment by arunoda** [comment] 2015-07-28 22:41
Hey @zimt28 I tried to reproduce this but I couldn't. Try using the latest version?
Is it possible to create a repo with the issue.
Then that's easy for me.

**Comment by delgermurun** [comment] 2015-09-27 10:43
I can't reproduce it too.

**Comment by arunoda** [comment] 2015-09-28 20:38
closing because we don't have a reproducible repo.

**Closed** 2015-09-28 20:38 UTC
