### ISSUE TITLE
Upgrade to Meteor 1.3 beta 5 throws error for FlowRouter-SSR

### ISSUE THREAD

**Issue by jasongrishkoff** [kadirahq/flow-router#505] opened 2016-01-27 14:46 UTC
Getting this error after upgrading to beta 5.  Using the latest version of FlowRouter-ssr (3.9.0)

packages/kadira:flow-router-ssr/lib/router.js:43:8: /packages/kadira:flow-router-ssr/lib/router.js: Duplicate declaration "path"

Rolling back to beta 4 solved the issue.

**Comment by SylarRuby** [comment] 2016-01-28 10:17
Clearly the issue is not resolved. Rolling back only avoided the issue.

**Comment by arunoda** [comment] 2016-01-28 10:55
Here's the line: https://github.com/kadirahq/flow-router/blob/ssr/lib/router.js#L43
And clearly there is no issue. 

I wonder what's the issue here. Could you guys add an issue on meteor repo for this?

**Comment by PEM--** [comment] 2016-02-02 09:28
I've referenced the issue: https://github.com/meteor/meteor/issues/6138

**Comment by PEM--** [comment] 2016-02-02 09:54
In the meantime, I've created a small PR: https://github.com/kadirahq/flow-router/pull/515

**Comment by arunoda** [comment] 2016-02-03 05:15
This is fixed in version `v3.9.1`.

**Closed by arunoda** 2016-02-03 05:15 UTC

**Comment by PEM--** [comment] 2016-02-03 06:22
Thanks :+1:
