### ISSUE TITLE
Group Routes error

### ISSUE THREAD

**Issue by ansarizafar** [kadirahq/flow-router#263] opened 2015-08-09 15:51 UTC
I want to group all my public routes. I have defined my routes as under

```    
var publicRoutes = FlowRouter.group({
     prefix: '/'
 });

publicRoutes.route('/', {
 name: 'home',
 action: function() {
     BlazeLayout.render('mainLayout', {contents: 'HomePage'});
 }
 });
 publicRoutes.route('/signup', {
     name: 'signup',
     action: function() {
         BlazeLayout.render('mainLayout', {contents: 'SignUpPage'});
     }
 });
```
The home route is working fine where as I am getting "There is no route for the path: /signup" for the second route.

**Comment by Tyler-Anderson** [comment] 2015-08-09 18:34
I've had the same error and resorted to just using individual routes (not pleasant) i think the problem is we're misunderstanding the documentation somewhere. If someone explains it i'd be happy to update the docs (if needed)

**Comment by arunoda** [comment] 2015-08-12 06:17
@delgermurun could you have a look at this, if you got some time.

**Comment by churcho** [comment] 2015-08-18 15:57
The issue could be the prefix on the route definition. If you leave it blank it should be able to work.
```
var publicRoutes = FlowRouter.group({
    prefix: ''
});
```
I think the best use case scenario for groups would be `/admin, /public, /membersarea` basically named url prefixes. In this case having `prefix '/'` doesn't really make much sense since that would be the root and probably all routes inherit from this.

**Comment by delgermurun** [comment] 2015-09-27 10:29
Yeah, `prefix` should be empty, if it is root group. @Tyler-Anderson does it works? If so let's close.

**Comment by arunoda** [comment] 2015-09-28 20:37
I think we can close this.

**Closed** 2015-09-28 20:37 UTC
