### ISSUE TITLE
FlowRouter attaches/initializes Polymer/webcomponent custom elements three times.

### ISSUE THREAD

**Issue by AndreasGalster** [kadirahq/flow-router#390] opened 2015-11-09 19:09 UTC
This is in relation to this issue: 

https://github.com/Polymer/polymer/issues/2702 

Perhaps you can give your feedback on that issue what is happening in FlowRouter when DOM is attached to the page. I'm trying to file the major showstopper bugs with meteor + polymer / their webcomponents-lite polyfill

Thanks a lot!

**Comment by arunoda** [comment] 2015-11-10 02:50
Is there any reproducible repo?
Also, I am pretty new to WebComponents.

**Comment by AndreasGalster** [comment] 2015-11-10 03:40
I'll push someting to a repo ... WiFi is just super slow right now :/ I've looked a bit further into the issue though. It seems it breaks at BlazeLayout.render, or rather I think in Blaze.Render. However, I don't think it is directly breaking from Blaze.Render, since the webcomponent only gets initialized once when the template gets loaded, when I remove routing and just insert a standard template like it's done in the  'meteor create projectname' boilerplate project. 

I've console.logged a script in the same template along with the custom-element. The console in the normal script gets only called once, the custom element gets initialized three times. Could it be (based from what I looked at in the BlazeLayout file) that BlazeLayout append and destroys a template several times based on what route it switches to?

The guys at the other repo I linked to can probably give more insights on what might be the problem. ebidel mentioned that the webcomponents get initialized properly/just once with a normal bare bone element without meteor.

**Comment by AndreasGalster** [comment] 2015-11-10 04:30
https://github.com/AndreasGalster/PolymerFlowrouter 

I've pretty much made a mess out of the committing, I'm sure. Sorry, I'm still new to github :/

**Comment by arunoda** [comment] 2015-11-12 10:10
Hey, I tried your code and FlowRouter and BlazeLayout run properly and `applicationLayout` template only created one.

I assume, the issue is something related to polymer integration. 

I'm closing this issue and this is not FR specific. I also don't have expertise to debug polymer stuff.

**Closed by arunoda** 2015-11-12 10:10 UTC

**Comment by AndreasGalster** [comment] 2015-11-16 10:59
Hi arunoda, I think I found the reason for this: It's somewhat FR specific and somewhat Polymer specific. I'll have to investigate more when I have time.

If you look at my code I accidentally defined the landing route twice. I believe this is causing the DOM insertions to happen more than once. Obviously it's a mistake made by me but actually I'm wondering if this should happen?
