### ISSUE TITLE
how to config flow-layout for global or in route group?

### ISSUE THREAD

**Issue by thearabbit** [kadirahq/flow-router#122] opened 2015-05-23 07:06 UTC
how to config flow-layout for global (all route) or in route group?

**Comment by arunoda** [comment] 2015-05-24 05:03
There is no way to set it globally. You need to run it on each route's action. 
But, if you want you can run flow-layout inside a middleware as well.

**Comment by yuomtheara** [comment] 2015-05-24 07:55
Thanks, pl example.

**Comment by michaelevensen** [comment] 2015-05-25 12:35
I'm curious about this myself. How do I define a global middleware? There's a possibility to define global subscriptions, but what if I want to check for a user field on all routes? Is this done on a route by route basis? Eg. would I have to apply a middleware to all my routes?

**Comment by abecks** [comment] 2015-09-22 21:42
So I've been looking into a way to do this, and I've come with a decent pattern. I'm brand new to Flow Router so I'm interested in @arunoda's opinion on the matter.

Using _.extend for shared defaults:

```js
// Default route options
var defaults = {
  layout: 'mainLayout',
  action: app.routes.action
};

// Home
FlowRouter.route('/', _.extend({}, defaults, {
  name: 'home'
}));
```

This allows easy DRY route definition, but the _.extend bit feels a bit verbose to me. 

I tried to find a way to do it in the new triggers system. The problem is that you can't assign arbitrary properties on a group:

```js
var publicRoutes = FlowRouter.group({
  name: 'public',
  layout: 'mainLayout'
});

// Home
publicRoutes.route('/',  {
  name: 'home'
});

FlowRouter.triggers.enter([
  function(context){
    console.log(context.route.group.layout); // undefined
  }
]);
```

So I would have to say it's not possible in a trigger yet, but I could be wrong. @arunoda would you mind weighing in when you have some time?

**Comment by arunoda** [comment] 2015-10-14 09:12
I close this because this is a question. Feel free to discuss.

**Closed by arunoda** 2015-10-14 09:12 UTC
Labels: question
