### ISSUE TITLE
IE8 support

### ISSUE THREAD

**Issue by tomwasd** [kadirahq/flow-router#264] opened 2015-08-10 12:23 UTC
Hi,

Thanks for sorting out IE9 - that works nicely now thanks!

I think I've managed to get IE8 working in a small test app that I've made.

The only changes required to flow-router would be to create weak dependencies on two packages (so that if the user adds them they're definitely loaded before flow-router).

    api.use('tomwasd:history-polyfill', {weak: true});
    api.use('tomwasd:flow-router-ie8', {weak: true});

You can see an example here: http://www.github.com/tomwasd/flow-router

My version of the history-polyfill uses the latest version of the history polyfill (https://github.com/devote/HTML5-History-API). tmeasday's package uses an older version of the polyfill that seemed to cause an infinite redirect loop in IE8.

The flow-router-ie8 package adds the three polyfills required to get page.js working: one for event listeners, one for Object.create and another for forEach. The polyfills are all those recommended on the MDN site.

Edit: looks like a couple more polyfills are required for isArray and Object.keys - I've added these to the package.

The packages are on github and atmosphere. Afraid I haven't done very extensive tests - just enough to see that it actually loads the page and navigates on my site which is the extent of IE8 support I need.

https://github.com/tomwasd/flow-router-ie8
https://github.com/tomwasd/history-polyfill

Not sure if you want to add IE8 into core but this will hopefully be useful if anyone else reading wants to try and hack in their own IE8 support.

**Comment by arunoda** [comment] 2015-08-12 06:15
I think we don't need anything from the FR layer for this. Of course we can ask use your wrapper. How about using [Autopublish](https://autopublish.meteor.com/) for the history polyfill. 

If you can work on that, that's super awesome.
May be @alanning also interested in it.

**Comment by alanning** [comment] 2015-08-12 14:44
Yes, I'd be interested in helping out.  Seems like the only change to FR would be to update [this section](https://github.com/kadirahq/flow-router#ie9-support) in the readme.  I can do a PR for that if you'd like.  Adding the weak package references would be best since then load order will be handled automatically but that's not required.

I think there's also some tests missing since the complete FR test suite was passing for me and @pahans in IE9 even though @tomwasd [reported](https://github.com/kadirahq/flow-router/issues/254) that clicking links didn't work in a real app.  Not sure if anything needs to be tested specifically for IE8 but at least we should do something for IE9 to help prevent future regressions.

Autopublish looks pretty cool.  Looks like you just have to add their userbot to your org and it can publish for you.

**Comment by arunoda** [comment] 2015-08-12 15:30
Hi,

It was an issue with the clicking. I think it's hard to write a test case
for that.

We fixed it.

I think I will stay away from adding it as a weak dependency. We can add a
proper read me asking to add it before the flow-router.

**Comment by arunoda** [comment] 2015-08-16 13:31
Closing this and waiting for the PR to the README.

**Closed by arunoda** 2015-08-16 13:31 UTC
